services:
  web: 
    build: "./"
    depends_on:
      - db
    ports: 
      - "8080:8080"
    restart: always
    volumes: 
      - "./tests:/srv/tests"
      - "./wagtail_trash:/srv/wagtail_trash"
      - "./settings_dev.py:/srv/settings_dev.py"
      - "./manage.py:/srv/manage.py"
      - "./runtests.py:/srv/runtests.py"
    working_dir: /srv
    environment:
      - DATABASE_HOST=db
  db:
    image: postgis/postgis:13-3.4
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
